### ISSUE TITLE
Build fails on OSX 10.12.6

### ISSUE THREAD

**Issue by ixemad** [melgi/cturtle#11] opened 2018-11-19 07:31 UTC
This was the error

```
c++ -c  -O2 -Wall -march=native -std=c++11 -o obj/Utf8.o src/Utf8.cc
In file included from src/Utf8.cc:18:
src/Utf8.hh:27:8: error: no type named 'size_t' in namespace 'std'
                std::size_t encode(char32_t c, OutputIterator i)
                ~~~~~^
src/Utf8.hh:29:9: error: no type named 'size_t' in namespace 'std'
                        std::size_t size = 0;
                        ~~~~~^
src/Utf8.hh:108:49: error: no type named 'size_t' in namespace 'std'
                        template<typename InputIterator> friend std::size_t decode(char32_t *c32, InputIterator begin, InputIterator end, State *state);
                                                                ~~~~~^
src/Utf8.hh:112:8: error: no type named 'size_t' in namespace 'std'
                std::size_t decode(char32_t *c32, InputIterator begin, InputIterator end, State *state)
                ~~~~~^
4 errors generated.
make: *** [obj/Utf8.o] Error 1
```

I fixed up this error adding this `#include <cstddef>` line in src/Utf8.hh file as explained in [this stackoverflow answer](https://stackoverflow.com/a/24458188). I hope it helps.

**Comment by melgi** [comment] 2019-01-14 21:45
Thanks,

The issue is a duplicate of #8, but the fix was not included in version 1.0.5.
Version 1.0.6 includes it now.

**Closed as completed by melgi** 2019-01-14 21:45 UTC
